
CREATE TABLE HISTORY (
             ID_HIS NUMBER(10) NOT NULL,
             ID_USER NUMBER(10) NOT NULL,  
             NAME_TABLE NUMBER(10),
			 STATUS VARCHAR2 (1000),
			 DATE_UPDATE DATE,
            FOREIGN KEY ("ID_USER") REFERENCES "USER" ("ID_USER") ON DELETE SET NULL			 
);