CREATE TABLE ROLE (
  ID_ROLE NUMBER(5,0) NOT NULL,
  NAME VARCHAR2(6) NOT NULL,
  CONSTRAINT ID_ROLE_ID PRIMARY KEY (ID_ROLE)
  );
  
CREATE TABLE "USER" (
  ID_USER   NUMBER(10,0) NOT NULL,
  NAME    VARCHAR2(10) NOT NULL,
  SURNAME          VARCHAR2(25) NOT NULL,
  OTCHESTVO  VARCHAR2(20) NOT NULL,
  BORN     DATE        NOT NULL,
  PHONE    VARCHAR2(11),
  EMAIL    VARCHAR2(25),
  ID_ROLE    NUMBER(5,0),
  CONSTRAINT ID_USER_PK PRIMARY KEY (ID_USER),
 FOREIGN KEY (ID_ROLE) REFERENCES ROLE (ID_ROLE)   
);

CREATE TABLE PRODUCT 
    ( 
     DESCRIPTION VARCHAR2 (2000) , 
     ID_PRODUCT NUMBER (5) NOT NULL , 
     NAME VARCHAR2 (30)  NOT NULL , 
     PRICE DECIMAL (18,4), 
     CONSTRAINT ID_PRODUCT_PK PRIMARY KEY (ID_PRODUCT)
    )  
;

CREATE TABLE OPINION (
             ID_OPINION NUMBER(5) NOT NULL,
             ID_PRODUCT NUMBER(5) NOT NULL,
             ID_USER NUMBER(10,0) NOT NULL,
             TEXT VARCHAR2(2000) NOT NULL,
             CONSTRAINT ID_OPINION_PK PRIMARY KEY (ID_OPINION),
             FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT),
             FOREIGN KEY (ID_USER) REFERENCES "USER" (ID_USER)
);

CREATE TABLE "CATALOG"
    ( 
     ID_CATALOG NUMBER (5)  NOT NULL , 
     ID_PARENT NUMBER (5)  , 
     NAME VARCHAR2 (20) ,
     ID_PRODUCT NUMBER (5) ,
     CONSTRAINT ID_CATALOG_PK PRIMARY KEY (ID_CATALOG),
     FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT) 
    )
;

CREATE TABLE IMAGE (
             ID_IMG NUMBER(5) NOT NULL,
             ID_PRODUCT NUMBER(5) NOT NULL,
             NAME VARCHAR2(20) NOT NULL,
             "PATH" BFILE NOT NULL,
             WIDTH NUMBER(4) NOT NULL,
             HEIGHT NUMBER (4) NOT NULL, 
             EXTENSION VARCHAR2(4) NOT NULL,
             CONSTRAINT ID_IMG_PK PRIMARY KEY (ID_IMG),
             FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)
);
CREATE TABLE "ORDER" (
			ID_ORDER NUMBER(5,0) NOT NULL,
			ID_USER NUMBER(10,0) NOT NULL,
			ID_PRODUCT NUMBER(5,0) NOT NULL,
			STATUS NUMBER(1,0) NOT NULL,
			KOL_VO NUMBER(10,0) NOT NULL,
			CONSTRAINT ID_ORDER PRIMARY KEY(ID_ORDER),
			FOREIGN KEY ("ID_USER") REFERENCES "USER" ("ID_USER"),
			FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)
);

