CREATE SEQUENCE MY_SEQ_C
  INCREMENT BY 1
    START WITH 41
    ;
CREATE OR REPLACE TRIGGER MY_TRIGGER_C
BEFORE INSERT ON "CATALOG"
FOR EACH ROW
BEGIN
SELECT MY_SEQ_C.NEXTVAL INTO :NEW.ID_CATALOG FROM dual;
END;
/

CREATE SEQUENCE MY_SEQ_I
  INCREMENT BY 1
    START WITH 1
    ;
CREATE OR REPLACE TRIGGER MY_TRIGGER_I
BEFORE INSERT ON IMAGE
FOR EACH ROW
BEGIN
SELECT MY_SEQ_I.NEXTVAL INTO :NEW.ID_IMG FROM dual;
END;
/

CREATE SEQUENCE MY_SEQ_O
  INCREMENT BY 1
    START WITH 1
    ;
CREATE OR REPLACE TRIGGER MY_TRIGGER_O
BEFORE INSERT ON OPINION
FOR EACH ROW
BEGIN
SELECT MY_SEQ_O.NEXTVAL INTO :NEW.ID_OPINION FROM dual;
END;
/

CREATE SEQUENCE MY_SEQ_ORD
  INCREMENT BY 1
    START WITH 1
    ;
CREATE OR REPLACE TRIGGER MY_TRIGGER_ORD
BEFORE INSERT ON "ORDER"
FOR EACH ROW
BEGIN
SELECT MY_SEQ_ORD.NEXTVAL INTO :NEW.ID_ORDER FROM dual;
END;
/

CREATE SEQUENCE MY_SEQ_P
  INCREMENT BY 1
    START WITH 130
    ;
CREATE OR REPLACE TRIGGER MY_TRIGGER_P
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
SELECT MY_SEQ_P.NEXTVAL INTO :NEW.ID_PRODUCT FROM dual;
END;
/

CREATE SEQUENCE MY_SEQ_R
  INCREMENT BY 1
    START WITH 1
    ;
CREATE OR REPLACE TRIGGER MY_TRIGGER_R
BEFORE INSERT ON "ROLE" 
FOR EACH ROW
BEGIN
SELECT MY_SEQ_R.NEXTVAL INTO :NEW.ID_ROLE FROM dual;
END;
/

CREATE SEQUENCE MY_SEQ_U
  INCREMENT BY 1
    START WITH 16
	;
CREATE OR REPLACE TRIGGER MY_TRIGGER_U
BEFORE INSERT ON "USER" 
FOR EACH ROW
BEGIN
SELECT MY_SEQ_U.NEXTVAL INTO :NEW.ID_USER FROM dual;
END;
/
CREATE SEQUENCE MY_SEQ_H
  INCREMENT BY 1
    START WITH 1
	;
