DROP TABLE CATALOGS;
DROP TABLE IMAGE;
DROP TABLE PRODUCT;
DROP TABLE USERS;
DROP TABLE ROLE;


CREATE TABLE ROLE (
  ID NUMBER(5,0) NOT NULL,
  NAME VARCHAR2(6) NOT NULL,
  CONSTRAINT PK_ROLE_ID PRIMARY KEY (ID)
  );
  
CREATE TABLE USERS (
  ID    NUMBER(10,0) NOT NULL,
  NAME    VARCHAR2(10) NOT NULL,
  SURNAME          VARCHAR2(25) NOT NULL,
  OTCHESTVO  VARCHAR2(20) NOT NULL,
  BORN     DATE        NOT NULL,
  PHONE    VARCHAR2(11),
  EMAIL    VARCHAR2(25),
  ID_ROLE    NUMBER(5,0),
  CONSTRAINT ID_USER_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_ROLE) REFERENCES ROLE (ID)   
);


CREATE TABLE PRODUCT 
    ( 
     DESCRIPTION VARCHAR2 (2000) , 
     ID_PRODUCT NUMBER (5) NOT NULL , 
     NAME VARCHAR2 (30)  NOT NULL , 
     PRICE DECIMAL (18,4), 
     
     CONSTRAINT ID_PRODUCT_PK PRIMARY KEY (ID_PRODUCT)
    )  
;

CREATE TABLE CATALOGS
    ( 
     ID_CATALOG NUMBER (5)  NOT NULL , 
     ID_PARENT NUMBER (5)  , 
     NAME VARCHAR2 (20) ,
     ID_PRODUCT NUMBER (5) ,
     CONSTRAINT ID_CATALOG_PK PRIMARY KEY (ID_CATALOG),
     FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT) 
    )
;

CREATE TABLE IMAGE (
             ID_IMG NUMBER(5) NOT NULL,
             ID_PRODUCT NUMBER(5) NOT NULL,
             NAME VARCHAR2(20) NOT NULL,
             "PATH" BFILE NOT NULL,
             WIDTH NUMBER(4) NOT NULL,
             HEIGHT NUMBER (4) NOT NULL, 
             EXTENSION VARCHAR2(4) NOT NULL,
             CONSTRAINT ID_IMG_PK PRIMARY KEY (ID_IMG),
             FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)
);
