CREATE SEQUENCE MY_SEQ_C
	INCREMENT BY 1
  	START WITH 1
  	;
CREATE OR REPLACE TRIGGER MY_TRIGGER_C
BEFORE INSERT ON "CATALOG"
FOR EACH ROW
BEGIN
SELECT MY_SEQ_C.NEXTVAL INTO :NEW.ID_CATALOG FROM dual;
END;
/

