CREATE SEQUENCE MY_SEQ_ORD
	INCREMENT BY 1
  	START WITH 1
  	;
CREATE OR REPLACE TRIGGER MY_TRIGGER_ORD
BEFORE INSERT ON "ORDER"
FOR EACH ROW
BEGIN
SELECT MY_SEQ_ORD.NEXTVAL INTO :NEW.ID_ORDER FROM dual;
END;
/

