CREATE SEQUENCE MY_SEQ_P
	INCREMENT BY 1
  	START WITH 1
  	;
CREATE OR REPLACE TRIGGER MY_TRIGGER_P
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
SELECT MY_SEQ_P.NEXTVAL INTO :NEW.ID_PRODUCT FROM dual;
END;
/

