CREATE SEQUENCE MY_SEQ_R
	INCREMENT BY 1
  	START WITH 1
  	;
CREATE OR REPLACE TRIGGER MY_TRIGGER_R
BEFORE INSERT ON "ROLE" 
FOR EACH ROW
BEGIN
SELECT MY_SEQ_R.NEXTVAL INTO :NEW.ID_ROLE FROM dual;
END;
/

