CREATE SEQUENCE MY_SEQ_U
	INCREMENT BY 1
  	START WITH 1
  	MAXVALUE 99;
CREATE OR REPLACE TRIGGER MY_TRIGGER_U
BEFORE INSERT ON "USER" 
FOR EACH ROW
BEGIN
SELECT MY_SEQ_U.NEXTVAL INTO :NEW.ID_USER FROM dual;
END;
/

